import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ImportWidgetProps extends React.ScriptHTMLAttributes<HTMLScriptElement> {
  customAttribute?: string;
  communityId: string;
  sampleQuestions: string[];
  communityName: string;
}

const ImportWidgetScript: React.FC = () => {
  const customProps: ImportWidgetProps = {
    src: "https://example.com/script.js",
    communityId: "1-15",
    sampleQuestions: ["What is Bloxroute?", "How to start with Bloxroute?"],
    communityName: "Bloxroute"
  };

  return <script {...customProps}></script>;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
        <script
          src="https://demo-staging.d1hlqxzsj0hfwo.amplifyapp.com/widget-import.js"
          data-community-id="1-15"
          data-sample-questions='["What is Bloxroute?", "How to start with Bloxroute?"]'
          data-community-name="Bloxroute"
        ></script>
      </body>
    </html>
  );
}
