import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
        <script
          src="https://demo-staging.d1hlqxzsj0hfwo.amplifyapp.com/widget-import.js"
          communityId="1-15"
          sampleQuestions='["What is Bloxroute?", "How to start with Bloxroute?"]'
          communityName="Bloxroute"
        ></script>
      </body>
    </html>
  );
}
